# Generated by Django 5.2.11 on 2026-02-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INFIRMIER', 'Infirmier'), ('MEDECIN_TRAVAIL', 'Médecin du travail'), ('MEDECIN_TRAITANT', 'Médecin traitant'), ('MEDECIN_CONTROLEUR', 'Médecin contrôleur'), ('RESPONSABLE_RH', 'Responsable RH'), ('AGENT_HSEE', 'Agent HSEE')], default='INFIRMIER', max_length=30),
        ),
    ]
