# Generated by Django 5.2.11 on 2026-03-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_collaborateur_remove_user_actif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localite', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborateurs', to='accounts.site'),
        ),
    ]
