# Generated by Django 5.2.11 on 2026-03-04 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_site_collaborateur_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='site',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborateurs', to='accounts.site'),
        ),
    ]
