# Generated by Django 5.2.11 on 2026-03-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_collaborateur_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='cin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='departement',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='poste',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
