# Generated by Django 5.2.11 on 2026-03-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_collaborateur_adresse_collaborateur_cin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
