# Generated by Django 5.2.11 on 2026-03-06 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_collaborateur_site'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_medecin', models.CharField(choices=[('TRAITANT', 'Médecin traitant'), ('TRAVAIL', 'Médecin du travail'), ('CONTROLEUR', 'Médecin contrôleur')], max_length=20)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('TERMINE', 'Terminé'), ('REPORTE', 'Reporté'), ('ANNULE', 'Annulé')], default='PREVU', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv', to='accounts.collaborateur')),
            ],
        ),
        migrations.DeleteModel(
            name='RendezVous',
        ),
    ]
