from django.urls import path
from .views import (
    DossierByCollaborateurView,
    DossierByMatriculeView,
    DossierAutofillView,
    DossierAutofillOneView,
    ExamenInitialCreateUpdateView,
    VaccinationCreateView,
    VaccinationDeleteView,
    IncidentListCreateView,
    IncidentDetailView,
    AccidentListCreateView,
    AccidentDetailView,
    AccidentStatsView,
    AccidentSendToHSEEView,
    HSEEAccidentsListView,
    HSEEKpisView,
    HSEETopCausesView,
    HSEEAccidentsParSegmentView,
    HSEEAccidentsParGraviteView,
    HSEEAccidentsParMoisView,
    HSEEPlanActionView,
    MaladieCreateView,
    MaladieDeleteView,
    PosteCreateView,
    PosteDeleteView,
    ExamenUlterieurCreateView,
    ExamenUlterieurDeleteView,
    FicheMedicaleByCollaborateurView,
    OrdonnanceListCreateByCollaborateurView,
    CertificatListCreateByCollaborateurView,
    StockItemListCreateAPIView,
    StockItemDetailAPIView,
    StockMovementListCreateAPIView,
    ControleMedicalRecordListCreateView,
    DemandeExpertiseRecordListCreateView,
    MedecinControleurReportView,
    DemandeExamenLaboListCreateByCollaborateurView,
    ExamenComplementaireListCreateByCollaborateurView,
    FicheAptitudePdfView,
    CertificatMedicalPdfView,
    OrdonnancePdfView,
    AccidentTravailPdfView,
    MaladieProfessionnellePdfView,
)

urlpatterns = [
    path("fiche-aptitude/<int:pk>/pdf/", FicheAptitudePdfView.as_view()),
    path("certificats/<int:pk>/pdf/", CertificatMedicalPdfView.as_view()),
    path("ordonnances/<int:pk>/pdf/", OrdonnancePdfView.as_view()),
    path("accidents-travail/<int:pk>/pdf/", AccidentTravailPdfView.as_view()),
    path("maladies-professionnelles/<int:pk>/pdf/", MaladieProfessionnellePdfView.as_view()),

    path("dossier/<int:collaborateur_id>/", DossierByCollaborateurView.as_view()),
    path("dossier/matricule/<str:matricule>/", DossierByMatriculeView.as_view()),
    path("dossiers/autofill/", DossierAutofillView.as_view()),
    path("dossier/<int:collaborateur_id>/autofill/", DossierAutofillOneView.as_view()),
    path("examens-labo/<int:collaborateur_id>/", DemandeExamenLaboListCreateByCollaborateurView.as_view()),
    path("examens-complementaires/<int:collaborateur_id>/", ExamenComplementaireListCreateByCollaborateurView.as_view()),
    path("examens-initial/", ExamenInitialCreateUpdateView.as_view()),
    path("examens-initial/<int:pk>/", ExamenInitialCreateUpdateView.as_view()),

    path("vaccinations/", VaccinationCreateView.as_view()),
    path("vaccinations/<int:pk>/", VaccinationDeleteView.as_view()),

    path("incidents/", IncidentListCreateView.as_view()),
    path("incidents/<int:pk>/", IncidentDetailView.as_view()),

    path("accidents-travail/", AccidentListCreateView.as_view()),
    path("accidents-travail/stats/", AccidentStatsView.as_view()),
    path("accidents-travail/<int:pk>/", AccidentDetailView.as_view()),
    path("accidents-travail/<int:pk>/send-hsee/", AccidentSendToHSEEView.as_view()),

    path("hsee/accidents/", HSEEAccidentsListView.as_view()),
    path("hsee/kpis/", HSEEKpisView.as_view()),
    path("hsee/top-causes/", HSEETopCausesView.as_view()),
    path("hsee/accidents-par-segment/", HSEEAccidentsParSegmentView.as_view()),
    path("hsee/accidents-par-gravite/", HSEEAccidentsParGraviteView.as_view()),
    path("hsee/accidents-par-mois/", HSEEAccidentsParMoisView.as_view()),
    path("hsee/plan-action/", HSEEPlanActionView.as_view()),

    path("maladies-professionnelles/", MaladieCreateView.as_view()),
    path("maladies-professionnelles/<int:pk>/", MaladieDeleteView.as_view()),

    path("postes-travail/", PosteCreateView.as_view()),
    path("postes-travail/<int:pk>/", PosteDeleteView.as_view()),

    path("examens-ulterieurs/", ExamenUlterieurCreateView.as_view()),
    path("examens-ulterieurs/<int:pk>/", ExamenUlterieurDeleteView.as_view()),

    path("fiche/<int:collaborateur_id>/", FicheMedicaleByCollaborateurView.as_view()),
    path("ordonnances/<int:collaborateur_id>/", OrdonnanceListCreateByCollaborateurView.as_view()),
    path("certificats/<int:collaborateur_id>/", CertificatListCreateByCollaborateurView.as_view()),

    path("stock/items/", StockItemListCreateAPIView.as_view()),
    path("stock/items/<int:pk>/", StockItemDetailAPIView.as_view()),
    path("stock/movements/", StockMovementListCreateAPIView.as_view()),
    path("medecin-controleur/controles/", ControleMedicalRecordListCreateView.as_view()),
    path("medecin-controleur/expertises/", DemandeExpertiseRecordListCreateView.as_view()),
    path("medecin-controleur/rapport/", MedecinControleurReportView.as_view()),
]
