from django.urls import path
from .views import (
    DossierByCollaborateurView,
    DossierByMatriculeView,
    DossierAutofillView,
    DossierAutofillOneView,
    ExamenInitialCreateUpdateView,
    VaccinationCreateView,
    VaccinationDeleteView,
    IncidentListCreateView,
    IncidentDetailView,
    IncidentAvecBonListCreateView,
    IncidentAvecBonDetailView,
    IncidentSansBonListCreateView,
    IncidentSansBonDetailView,
    BonChauffeurListCreateView,
    BonChauffeurDetailView,
    SuiviTransfertUrgenceListCreateView,
    SuiviTransfertUrgenceDetailView,
    AccidentListCreateView,
    AccidentDetailView,
    AccidentStatsView,
    AccidentSendToHSEEView,
    EnqueteInitialeAccidentListCreateView,
    EnqueteInitialeAccidentDetailView,
    EnqueteInitialeAccidentPdfView,
    EnqueteInitialeAccidentSendToHSEEView,
    HSEEAccidentsListView,
    HSEEEnquetesReceivedListView,
    HSEETransmissionListCreateView,
    HSEETransmissionDetailView,
    HSEETransmissionPdfView,
    HSEEDashboardDataView,
    HSEEKpisView,
    HSEETopCausesView,
    HSEEAccidentsParSegmentView,
    HSEEAccidentsParGraviteView,
    HSEEAccidentsParMoisView,
    HSEEPlanActionView,
    HSEEEnqueteListCreateView,
    HSEEReportsDashboardStatsView,
    HSEEReportTemplatesView,
    HSEEReportTemplateDetailView,
    HSEEGeneratedReportsView,
    HSEEGenerateReportView,
    HSEEPreviewReportPayloadView,
    HSEEGeneratedReportPreviewView,
    HSEEGeneratedReportDownloadView,
    HSEEGeneratedReportSendView,
    MaladieCreateView,
    MaladieDeleteView,
    PosteCreateView,
    PosteDeleteView,
    ExamenUlterieurCreateView,
    ExamenUlterieurDeleteView,
    FicheMedicaleByCollaborateurView,
    OrdonnanceListCreateByCollaborateurView,
    CertificatListCreateByCollaborateurView,
    StockItemListCreateAPIView,
    StockItemDetailAPIView,
    StockMovementListCreateAPIView,
    StockDashboardView,
    PointageMedecinListCreateView,
    PointageMedecinDetailView,
    PointageMedecinAnnualSummaryView,
    DemandeExamenLaboListCreateByCollaborateurView,
    ExamenComplementaireListCreateByCollaborateurView,
    FicheAptitudeListCreateByCollaborateurView,
    FicheAptitudeListCreateView,
    FicheAptitudeDetailView,
    ExamenLaboListCreateView,
    ExamenLaboDetailView,
    ExamenCompListCreateView,
    ExamenCompDetailView,
    DossierMedicalListCreateView,
    DossierMedicalDetailView,
    CollaborateurMedListCreateView,
    CollaborateurMedDetailView,
    FicheAptitudePdfView,
    DemandeExamenLaboPdfView,
    ExamenComplementairePdfView,
    DossierMedicalPdfView,
    CertificatMedicalPdfView,
    OrdonnancePdfView,
    AccidentTravailPdfView,
    MaladieProfessionnellePdfView,
)

urlpatterns = [
    path("fiches-aptitude/", FicheAptitudeListCreateView.as_view(), name="fiches-aptitude-list"),
    path("fiches-aptitude/<int:pk>/", FicheAptitudeDetailView.as_view(), name="fiches-aptitude-detail"),
    path("examens-labo/", ExamenLaboListCreateView.as_view(), name="examens-labo-list"),
    path("examens-labo/detail/<int:pk>/", ExamenLaboDetailView.as_view(), name="examens-labo-detail"),
    path("examens-complementaires/", ExamenCompListCreateView.as_view(), name="examens-comp-list"),
    path("examens-complementaires/detail/<int:pk>/", ExamenCompDetailView.as_view(), name="examens-comp-detail"),
    path("dossiers/", DossierMedicalListCreateView.as_view(), name="dossiers-list"),
    path("dossiers/<int:pk>/", DossierMedicalDetailView.as_view(), name="dossiers-detail"),
    path("collaborateurs/", CollaborateurMedListCreateView.as_view(), name="collab-med-list"),
    path("collaborateurs/<int:pk>/", CollaborateurMedDetailView.as_view(), name="collab-med-detail"),

    path("fiche-aptitude/<int:pk>/pdf/", FicheAptitudePdfView.as_view()),
    path("examens-labo/<int:pk>/pdf/", DemandeExamenLaboPdfView.as_view()),
    path("examens-complementaires/<int:pk>/pdf/", ExamenComplementairePdfView.as_view()),
    path("dossier/<int:pk>/pdf/", DossierMedicalPdfView.as_view()),
    path("certificats/<int:pk>/pdf/", CertificatMedicalPdfView.as_view()),
    path("ordonnances/<int:pk>/pdf/", OrdonnancePdfView.as_view()),
    path("accidents-travail/<int:pk>/pdf/", AccidentTravailPdfView.as_view()),
    path("maladies-professionnelles/<int:pk>/pdf/", MaladieProfessionnellePdfView.as_view()),

    path("dossier/<int:collaborateur_id>/", DossierByCollaborateurView.as_view()),
    path("dossier/matricule/<str:matricule>/", DossierByMatriculeView.as_view()),
    path("dossiers/autofill/", DossierAutofillView.as_view()),
    path("dossier/<int:collaborateur_id>/autofill/", DossierAutofillOneView.as_view()),
    path("examens-labo/<int:collaborateur_id>/", DemandeExamenLaboListCreateByCollaborateurView.as_view()),
    path("examens-complementaires/<int:collaborateur_id>/", ExamenComplementaireListCreateByCollaborateurView.as_view()),
    path("fiche-aptitude/<int:collaborateur_id>/", FicheAptitudeListCreateByCollaborateurView.as_view()),
    path("examens-initial/", ExamenInitialCreateUpdateView.as_view()),
    path("examens-initial/<int:pk>/", ExamenInitialCreateUpdateView.as_view()),

    path("vaccinations/", VaccinationCreateView.as_view()),
    path("vaccinations/<int:pk>/", VaccinationDeleteView.as_view()),

    path("incidents/", IncidentListCreateView.as_view()),
    path("incidents/<int:pk>/", IncidentDetailView.as_view()),
    path("incidents-avec-bon/", IncidentAvecBonListCreateView.as_view()),
    path("incidents-avec-bon/<int:pk>/", IncidentAvecBonDetailView.as_view()),
    path("incidents-sans-bon/", IncidentSansBonListCreateView.as_view()),
    path("incidents-sans-bon/<int:pk>/", IncidentSansBonDetailView.as_view()),
    path("bon-chauffeurs/", BonChauffeurListCreateView.as_view()),
    path("bon-chauffeurs/<int:pk>/", BonChauffeurDetailView.as_view()),
    path("suivi-transferts/", SuiviTransfertUrgenceListCreateView.as_view()),
    path("suivi-transferts/<int:pk>/", SuiviTransfertUrgenceDetailView.as_view()),

    path("accidents-travail/", AccidentListCreateView.as_view()),
    path("accidents-travail/stats/", AccidentStatsView.as_view()),
    path("accidents-travail/<int:pk>/", AccidentDetailView.as_view()),
    path("accidents-travail/<int:pk>/send-hsee/", AccidentSendToHSEEView.as_view()),
    path("enquetes-initiales/", EnqueteInitialeAccidentListCreateView.as_view()),
    path("enquetes-initiales/<int:pk>/", EnqueteInitialeAccidentDetailView.as_view()),
    path("enquetes-initiales/<int:pk>/pdf/", EnqueteInitialeAccidentPdfView.as_view()),
    path("enquetes-initiales/<int:pk>/send-hsee/", EnqueteInitialeAccidentSendToHSEEView.as_view()),
    path("enquetes-initiales/<int:pk>/send-to-hsee/", EnqueteInitialeAccidentSendToHSEEView.as_view()),

    path("hsee/accidents/", HSEEAccidentsListView.as_view()),
    path("hsee/enquetes-received/", HSEEEnquetesReceivedListView.as_view()),
    path("hsee-transmissions/", HSEETransmissionListCreateView.as_view()),
    path("hsee-transmissions/<int:pk>/", HSEETransmissionDetailView.as_view()),
    path("hsee-transmissions/<int:pk>/pdf/", HSEETransmissionPdfView.as_view()),
    path("hsee/dashboard/", HSEEDashboardDataView.as_view()),
    path("hsee/kpis/", HSEEKpisView.as_view()),
    path("hsee/top-causes/", HSEETopCausesView.as_view()),
    path("hsee/accidents-par-segment/", HSEEAccidentsParSegmentView.as_view()),
    path("hsee/accidents-par-gravite/", HSEEAccidentsParGraviteView.as_view()),
    path("hsee/accidents-par-mois/", HSEEAccidentsParMoisView.as_view()),
    path("hsee/plan-action/", HSEEPlanActionView.as_view()),
    path("hsee/enquetes/", HSEEEnqueteListCreateView.as_view()),
    path("hsee/reports/dashboard/", HSEEReportsDashboardStatsView.as_view()),
    path("hsee/reports/templates/", HSEEReportTemplatesView.as_view()),
    path("hsee/reports/templates/<str:template_id>/", HSEEReportTemplateDetailView.as_view()),
    path("hsee/reports/", HSEEGeneratedReportsView.as_view()),
    path("hsee/reports/generate/", HSEEGenerateReportView.as_view()),
    path("hsee/reports/preview/", HSEEPreviewReportPayloadView.as_view()),
    path("hsee/reports/<int:pk>/preview/", HSEEGeneratedReportPreviewView.as_view()),
    path("hsee/reports/<int:pk>/download/", HSEEGeneratedReportDownloadView.as_view()),
    path("hsee/reports/<int:pk>/send/", HSEEGeneratedReportSendView.as_view()),

    path("maladies-professionnelles/", MaladieCreateView.as_view()),
    path("maladies-professionnelles/<int:pk>/", MaladieDeleteView.as_view()),

    path("postes-travail/", PosteCreateView.as_view()),
    path("postes-travail/<int:pk>/", PosteDeleteView.as_view()),

    path("examens-ulterieurs/", ExamenUlterieurCreateView.as_view()),
    path("examens-ulterieurs/<int:pk>/", ExamenUlterieurDeleteView.as_view()),

    path("fiche/<int:collaborateur_id>/", FicheMedicaleByCollaborateurView.as_view()),
    path("ordonnances/<int:collaborateur_id>/", OrdonnanceListCreateByCollaborateurView.as_view()),
    path("certificats/<int:collaborateur_id>/", CertificatListCreateByCollaborateurView.as_view()),

    path("stock/items/", StockItemListCreateAPIView.as_view()),
    path("stock/items/<int:pk>/", StockItemDetailAPIView.as_view()),
    path("stock/movements/", StockMovementListCreateAPIView.as_view()),
    path("stock/dashboard/", StockDashboardView.as_view()),
    path("pointage-medecins/", PointageMedecinListCreateView.as_view()),
    path("pointage-medecins/summary/", PointageMedecinAnnualSummaryView.as_view()),
    path("pointage-medecins/<int:pk>/", PointageMedecinDetailView.as_view()),
]
