# Generated by Django 5.2.11 on 2026-03-01 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_collaborateur_remove_user_actif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('nb_jours_repos', models.PositiveIntegerField(default=0)),
                ('date_debut_repos', models.DateField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='accounts.collaborateur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('localite', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='accounts.collaborateur')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accident', models.DateField()),
                ('cause', models.TextField()),
                ('nature_lesion', models.CharField(max_length=255)),
                ('siege_lesion', models.CharField(max_length=255)),
                ('duree_arret', models.IntegerField(blank=True, null=True)),
                ('ipp', models.CharField(blank=True, max_length=100, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='medical.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenInitial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin_nom', models.CharField(max_length=255)),
                ('date_examen', models.DateField()),
                ('poids', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('tension_arterielle', models.CharField(blank=True, max_length=50, null=True)),
                ('pouls', models.CharField(blank=True, max_length=50, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_initial', to='medical.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenUlterieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('PERIODIQUE', 'Périodique'), ('REPRISE', 'Reprise de travail'), ('SPONTANE', 'Spontané')], max_length=50)),
                ('date', models.DateField()),
                ('medecin_nom', models.CharField(max_length=255)),
                ('poste_travail', models.CharField(blank=True, max_length=255, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_ulterieurs', to='medical.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='FicheMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=120, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_medicale', to='accounts.collaborateur')),
            ],
        ),
        migrations.CreateModel(
            name='MaladieProfessionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_maladie', models.CharField(max_length=255)),
                ('agent_causal', models.CharField(max_length=255)),
                ('numero_tableau', models.CharField(max_length=100)),
                ('date_decouverte', models.DateField()),
                ('duree_arret', models.IntegerField(blank=True, null=True)),
                ('ipp', models.CharField(blank=True, max_length=100, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maladies_professionnelles', to='medical.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='accounts.collaborateur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosteTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('risque_professionnel', models.TextField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='medical.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccin', models.CharField(max_length=255)),
                ('date_1', models.DateField(blank=True, null=True)),
                ('date_2', models.DateField(blank=True, null=True)),
                ('date_3', models.DateField(blank=True, null=True)),
                ('date_rappel', models.DateField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='medical.dossiermedical')),
            ],
        ),
    ]
