# Generated by Django 5.2.11 on 2026-03-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_article', models.CharField(choices=[('MEDICAMENT', 'Médicament'), ('CONSOMMABLE', 'Consommable')], max_length=20)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('seuil_critique', models.PositiveIntegerField(default=0)),
                ('unite', models.CharField(default='unité', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('remarque', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='medical.stockitem')),
            ],
        ),
    ]
