# Generated by Django 5.2.11 on 2026-03-06 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_stockitem_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidenttravail',
            name='circonstances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='envoye_hsee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='heure_accident',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='lieu_accident',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='temoin1_matricule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='temoin1_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='temoin1_telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='temoin2_matricule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='temoin2_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='temoin2_telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='transport_hopital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='IncidentInfirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_incident', models.DateField()),
                ('heure_incident', models.TimeField()),
                ('segment', models.CharField(blank=True, max_length=120, null=True)),
                ('unite', models.CharField(blank=True, max_length=50, null=True)),
                ('poste_occupe', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_lesion', models.CharField(max_length=255)),
                ('agent_causal', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('infirmier_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_infirmiers', to='medical.dossiermedical')),
            ],
        ),
    ]
