# Generated by Django 5.2.11 on 2026-03-06 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_accidenttravail_circonstances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidenttravail',
            name='gravite',
            field=models.CharField(blank=True, choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('GRAVE', 'Grave')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='segment',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='statut_enquete',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='PlanActionHSEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=255)),
                ('risque', models.CharField(max_length=255)),
                ('action', models.TextField()),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('delai', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='PLANIFIE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_action_hsee', to='medical.accidenttravail')),
            ],
        ),
    ]
