# Generated by Django 5.2.11 on 2026-03-08 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_collaborateur_site'),
        ('medical', '0004_accidenttravail_gravite_accidenttravail_segment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='alcool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents_chirurgicaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents_gynecologiques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents_heredofamiliaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents_medicaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='automedication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='date_recrutement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='niveau_etudes_diplomes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='poste_travail_actuel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='tabac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='abdomen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='appareil_cardio_vasculaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='appareil_genito_urinaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='appareil_locomoteur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='appareil_respiratoire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='aptitude',
            field=models.CharField(blank=True, choices=[('APTE', 'Apte'), ('APTE_AVEC_CONDITION', 'Apte avec condition'), ('INAPTE_POSTE', 'Inapte au poste'), ('INAPTE_DEFINITIF', 'Inapte définitif')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='audition_od',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='audition_og',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='denture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='examens_complementaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='glandes_endocrines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='precision_aptitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='resultat_examen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='systeme_nerveux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='teguments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='vision_od_loin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='vision_od_pres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='vision_og_loin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exameninitial',
            name='vision_og_pres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examenulterieur',
            name='audition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examenulterieur',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examenulterieur',
            name='vision_od',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examenulterieur',
            name='vision_og',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DemandeExamenLabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('cin', models.CharField(blank=True, max_length=50, null=True)),
                ('gsm', models.CharField(blank=True, max_length=50, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('poste_travail', models.CharField(blank=True, max_length=255, null=True)),
                ('renseignements_cliniques', models.TextField(blank=True, null=True)),
                ('glycemie', models.BooleanField(default=False)),
                ('creatinine', models.BooleanField(default=False)),
                ('nfs', models.BooleanField(default=False)),
                ('vs', models.BooleanField(default=False)),
                ('transaminases', models.BooleanField(default=False)),
                ('acide_urique', models.BooleanField(default=False)),
                ('triglycerides', models.BooleanField(default=False)),
                ('cholesterol', models.BooleanField(default=False)),
                ('examen_selles', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_examens_labo', to='accounts.collaborateur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_examens_labo_creees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('cin', models.CharField(blank=True, max_length=50, null=True)),
                ('poste_travail', models.CharField(blank=True, max_length=255, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('renseignements_cliniques', models.TextField(blank=True, null=True)),
                ('visiotest', models.BooleanField(default=False)),
                ('audiogramme', models.BooleanField(default=False)),
                ('ecg', models.BooleanField(default=False)),
                ('efr', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_complementaires', to='accounts.collaborateur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_complementaires_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FicheAptitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('nature_activite', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_cnss', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('date_lieu_naissance', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_travailleur', models.CharField(blank=True, max_length=255, null=True)),
                ('cnss_travailleur', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifications_professionnelles', models.CharField(blank=True, max_length=255, null=True)),
                ('date_recrutement', models.DateField(blank=True, null=True)),
                ('poste_travail', models.CharField(blank=True, max_length=255, null=True)),
                ('type_examen', models.CharField(choices=[('EMBAUCHE', 'Embauche'), ('PERIODIQUE', 'Périodique'), ('REPRISE', 'Reprise'), ('SPONTANE', 'Spontané')], max_length=30)),
                ('aptitude', models.CharField(choices=[('APTE', 'Apte'), ('APTE_AMENAGEMENT', 'Apte avec aménagement'), ('INAPTE_TEMPORAIRE', 'Inapte temporaire'), ('APTE_APRES_CHANGEMENT', 'Apte après changement du poste'), ('INAPTE_DEFINITIF', 'Inapte définitif')], max_length=40)),
                ('recommandations', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_aptitude', to='accounts.collaborateur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_aptitude_creees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
