# Generated by Django 5.2.11 on 2026-03-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_dossiermedical_alcool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenulterieur',
            name='audition',
        ),
        migrations.RemoveField(
            model_name='examenulterieur',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='examenulterieur',
            name='vision_od',
        ),
        migrations.RemoveField(
            model_name='examenulterieur',
            name='vision_og',
        ),
    ]
