# Generated by Django 5.2.12 on 2026-03-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_remove_examenulterieur_audition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidenttravail',
            name='activite_lieu',
            field=models.CharField(blank=True, choices=[('CHANTIER', 'Chantier'), ('ATELIER', 'Atelier'), ('BUREAU', 'Bureau'), ('AUTRE', 'Autre')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='activite_lieu_autre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='autres_victimes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='causes_materielles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='comment_accident',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='date_arret',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='description_circonstances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='employeur_activite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='employeur_adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='employeur_cnss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='employeur_code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='employeur_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='employeur_telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='heure_arret',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='horaire_travail_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='horaire_travail_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='nombre_travailleurs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='rapport_police',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='rapport_police_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='rapport_police_numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='rapport_police_poste',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='resultat',
            field=models.CharField(blank=True, choices=[('SANS_ARRET', 'Sans arrêt'), ('ARRET', 'Arrêt de travail'), ('DECES', 'Décès')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='salaire_duree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='salaire_maintenu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='salaire_montant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='salaire_unite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='signataire_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='signataire_qualite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='signature_lieu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='temoins',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='tiers_assureur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='tiers_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='tiers_responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_cin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_cnss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_lieu_travail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_nationalite',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_nom',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_nom_naissance',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_poste_accident',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_prenom',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_prenom_pere',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_sexe',
            field=models.CharField(blank=True, choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_situation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='victime_specialite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='arret_travail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='date_arret',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='date_arret_exposition',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='date_constat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='employeur_activite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='employeur_adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='employeur_cnss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='employeur_code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='employeur_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='employeur_telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='medecin_constat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='nature_travail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='salaire_duree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='salaire_maintenu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='salaire_montant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='salaire_unite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='signataire_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='signataire_qualite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='signature_lieu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='travaux_anterieurs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_cin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_cnss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_lieu_travail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_nationalite',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_nom',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_nom_naissance',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_prenom',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_prenom_pere',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_sexe',
            field=models.CharField(blank=True, choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_situation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='victime_specialite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
