# Generated by Django 5.2.12 on 2026-03-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_incidents_bon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('nom_chauffeur', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('medecin', models.CharField(blank=True, max_length=255, null=True)),
                ('infirmier', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_malade', models.CharField(max_length=255)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('service_plant', models.CharField(blank=True, max_length=255, null=True)),
                ('moyen_transport', models.CharField(blank=True, max_length=255, null=True)),
                ('hopital', models.CharField(blank=True, max_length=255, null=True)),
                ('accompagnant', models.CharField(blank=True, max_length=255, null=True)),
                ('montant_prime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviTransfertUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('chauffeur', models.CharField(max_length=255)),
                ('depart', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre_transport', models.CharField(blank=True, max_length=50, null=True)),
                ('plant', models.CharField(blank=True, max_length=120, null=True)),
                ('indemnite_deplacement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accidenttravail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maladieprofessionnelle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maladieprofessionnelle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
