# Generated by Django 5.2.12 on 2026-04-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_dossiermedical_add_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheaptitude',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='date_examen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='medecin_travail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
