# Generated by Django 5.2.12 on 2026-04-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_controlemedicalrecord_demandeexpertiserecord'),
        ('medical', '0014_pointage_medecin'),
    ]

    operations = [
    ]
