# Generated by Django 5.2.12 on 2026-04-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_repair_medical_schema_drift'),
        ('medical', '0018_hseegeneratedreport'),
    ]

    operations = [
    ]
