# Generated by Django 5.2.12 on 2026-06-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0021_medecin_controleur_history_pdf_filename'),
        ('medical', '0023_transmissionenquetehsee'),
    ]

    operations = [
    ]
