// src/lib/permissions.js
export const Permission = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  VIEW_COLLABORATEURS: "VIEW_COLLABORATEURS",
  VIEW_RDV: "VIEW_RDV",
  VIEW_ANALYSES: "VIEW_ANALYSES",
  VIEW_STOCK: "VIEW_STOCK",
  VIEW_USERS: "VIEW_USERS",
  VIEW_AUDIT: "VIEW_AUDIT",
  VIEW_PARAMETRES: "VIEW_PARAMETRES",
  VIEW_NOTIFICATIONS: "VIEW_NOTIFICATIONS",
  VIEW_DOSSIER_MEDICAL: "VIEW_DOSSIER_MEDICAL",
  EDIT_FICHE_MEDICALE: "EDIT_FICHE_MEDICALE",
  CREATE_ORDONNANCE: "CREATE_ORDONNANCE",
  CREATE_CERTIFICAT_MEDICAL: "CREATE_CERTIFICAT_MEDICAL",
  // (اختياري) إذا تستعملها في صفحات طبية
  VIEW_DOSSIER_MEDICAL: "VIEW_DOSSIER_MEDICAL",
};